auto: true
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]

pygments: true
markdown: rdiscount

description: 'I am an iOS developer in Columbus, OH that specializes in User Experience optimization. This is my blog that I use to rant, rave, and review various parts of my career.'
root_desc: 'Whoisryannystrom.com - iOS and development ponderings'

url: http://whoisryannystrom.com